### PR TITLE
version: use caret dependencies in Cargo.toml

### PR DESCRIPTION
**Pull request by studychao**
This is making sure that dependencies are not automatically updated when new ones are published and keeps the main branch always building.

Signed-off-by: Chao Wu <chaowu@linux.alibaba.com>

### Summary of the PR

*Please summarize here why the changes in this PR are needed.*

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Review by andreeaflorescu — APPROVED** [review]

**Review by lauralt — APPROVED** [review]

**Comment by roypat** [comment]
The CI failure is caused by https://github.com/rust-vmm/vmm-sys-util/commit/10a5ac19a0a898076d94512e633abfb010d0fb4d, which introduced a lot of Eq trait impls on error types, which is now causing clippy to complain about possible, but missing Eq implementations. We had the same issue in firecracker: https://github.com/firecracker-microvm/firecracker/pull/3252

**Comment by studychao** [comment]
Sorry I don't have enough capacity to follow up this PR. Will start working on this on Monday Morning China Time.

**Comment by studychao** [comment]
For the Clippy error in CI, I see there is already a PR #101 for it, so I will wait for it to be merged and rebase my PR.

For the Unit test error, I could not reproduce it in my environment, is there any way to retest the UT? @andreeaflorescu

**Comment by andreeaflorescu** [comment]
> For the Clippy error in CI, I see there is already a PR #101 for it, so I will wait for it to be merged and rebase my PR.

That makes sense, thanks.
 
> For the Unit test error, I could not reproduce it in my environment, is there any way to retest the UT? @andreeaflorescu

Looks like an intermittent error on the unit test. I re-ran it and it worked. We can investigate that later if it shows up again.

**Review by aghecenco — APPROVED** [review]

**Review by andreeaflorescu — APPROVED** [review]

**Pull request merged**
