### PR TITLE
Discards plans to implement iterator for pending IO events

### PR DESCRIPTION
**Pull request by jain98**
For details read discussion in https://github.com/rust-vmm/event-manager/issues/44

### CODE REVIEW

**Comment by jain98** [comment]
@andreeaflorescu / @jiangliu do you guys know why one of the unit tests for gnu-x86 might be failing?

**Comment by jain98** [comment]
H

> > @andreeaflorescu / @jiangliu do you guys know why one of the unit tests for gnu-x86 might be failing?
> 
> That case succeeds on my local dev machine, failure due to CI/CD env?

Had it passing in my local environment as well. Have we seen this issue with any other pull requests?

**Comment by lauralt** [comment]
We've seen it, but for another similar test (`test_register`); here is the issue: https://github.com/rust-vmm/event-manager/issues/29.

**Comment by lauralt** [comment]
I ran the tests in loop both on my local machine and on the test instance; and I saw the same error happening randomly, but pretty often. The tests that are failing are: `test_register`, `test_unregister` and `test_remove_subscriber` and the failure happens in random places, e.g https://github.com/rust-vmm/event-manager/blob/master/src/manager.rs#L372, https://github.com/rust-vmm/event-manager/blob/master/src/manager.rs#L424, https://github.com/rust-vmm/event-manager/blob/master/src/manager.rs#L306.

**Review by andreeaflorescu — APPROVED** [review]

**Comment by andreeaflorescu** [comment]
Since the failing tests are unrelated to your PR, I would propose to merge it. I re-ran the tests and now they pass. @alexandruag or @jiangliu can you help with a review here?

**Review by jiangliu — APPROVED** [review]

**Pull request merged**
